-- MySQL Script generated by MySQL Workbench
-- Mon Jan 31 17:58:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema datasikkerhet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema datasikkerhet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `datasikkerhet` DEFAULT CHARACTER SET utf8 ;
USE `datasikkerhet` ;

-- -----------------------------------------------------
-- Table `datasikkerhet`.`studieretning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datasikkerhet`.`studieretning` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `studieretning` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datasikkerhet`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datasikkerhet`.`student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `navn` VARCHAR(35) NOT NULL,
  `etternavn` VARCHAR(35) NOT NULL,
  `e_post` VARCHAR(45) NOT NULL,
  `passord` VARCHAR(255) NOT NULL,
  `studiekull` INT NOT NULL,
  `studieretning_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_student_studieretning1_idx` (`studieretning_id` ASC),
  CONSTRAINT `fk_student_studieretning1`
    FOREIGN KEY (`studieretning_id`)
    REFERENCES `datasikkerhet`.`studieretning` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datasikkerhet`.`foreleser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datasikkerhet`.`foreleser` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `navn` VARCHAR(35) NOT NULL,
  `etternavn` VARCHAR(35) NOT NULL,
  `e_post` VARCHAR(45) NOT NULL,
  `passord` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datasikkerhet`.`gjest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datasikkerhet`.`gjest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brukernavn` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datasikkerhet`.`bilde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datasikkerhet`.`bilde` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bilde_navn` VARCHAR(100) NOT NULL,
  `file_destination` VARCHAR(255) NOT NULL,
  `foreleser_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bilde_foreleser1_idx` (`foreleser_id` ASC),
  CONSTRAINT `fk_bilde_foreleser1`
    FOREIGN KEY (`foreleser_id`)
    REFERENCES `datasikkerhet`.`foreleser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datasikkerhet`.`emne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datasikkerhet`.`emne` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `navn` VARCHAR(25) NOT NULL,
  `pin_kode` INT(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datasikkerhet`.`tilbakemelding_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datasikkerhet`.`tilbakemelding_student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tidspunkt` DATETIME(6) NOT NULL,
  `tilbakemelding` VARCHAR(500) NOT NULL,
  `svar_gitt_foreleser` INT NOT NULL,
  `emne_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tilbakemelding_student_emne1_idx` (`emne_id` ASC),
  INDEX `fk_tilbakemelding_student_student1_idx` (`student_id` ASC),
  CONSTRAINT `fk_tilbakemelding_student_emne1`
    FOREIGN KEY (`emne_id`)
    REFERENCES `datasikkerhet`.`emne` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tilbakemelding_student_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `datasikkerhet`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datasikkerhet`.`svar_foreleser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datasikkerhet`.`svar_foreleser` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tidspunkt` DATETIME(6) NOT NULL,
  `svar` VARCHAR(255) NOT NULL,
  `tilbakemelding_student_id` INT NOT NULL,
  `foreleser_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_svar_foreleser_tilbakemelding_student1_idx` (`tilbakemelding_student_id` ASC),
  INDEX `fk_svar_foreleser_foreleser1_idx` (`foreleser_id` ASC),
  CONSTRAINT `fk_svar_foreleser_tilbakemelding_student1`
    FOREIGN KEY (`tilbakemelding_student_id`)
    REFERENCES `datasikkerhet`.`tilbakemelding_student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_svar_foreleser_foreleser1`
    FOREIGN KEY (`foreleser_id`)
    REFERENCES `datasikkerhet`.`foreleser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datasikkerhet`.`kommentar_gjest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datasikkerhet`.`kommentar_gjest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tidspunkt` DATETIME(6) NOT NULL,
  `kommentar` VARCHAR(255) NOT NULL,
  `tilbakemelding_student_id` INT NOT NULL,
  `gjest_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kommentar_gjest_tilbakemelding_student1_idx` (`tilbakemelding_student_id` ASC),
  INDEX `fk_kommentar_gjest_gjest1_idx` (`gjest_id` ASC),
  CONSTRAINT `fk_kommentar_gjest_tilbakemelding_student1`
    FOREIGN KEY (`tilbakemelding_student_id`)
    REFERENCES `datasikkerhet`.`tilbakemelding_student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kommentar_gjest_gjest1`
    FOREIGN KEY (`gjest_id`)
    REFERENCES `datasikkerhet`.`gjest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datasikkerhet`.`foreleser_has_emne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datasikkerhet`.`foreleser_has_emne` (
  `foreleser_id` INT NOT NULL,
  `emne_id` INT NOT NULL,
  PRIMARY KEY (`foreleser_id`, `emne_id`),
  INDEX `fk_foreleser_has_emne_emne1_idx` (`emne_id` ASC),
  INDEX `fk_foreleser_has_emne_foreleser1_idx` (`foreleser_id` ASC),
  CONSTRAINT `fk_foreleser_has_emne_foreleser1`
    FOREIGN KEY (`foreleser_id`)
    REFERENCES `datasikkerhet`.`foreleser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_foreleser_has_emne_emne1`
    FOREIGN KEY (`emne_id`)
    REFERENCES `datasikkerhet`.`emne` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `datasikkerhet`.`studieretning_has_emne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datasikkerhet`.`studieretning_has_emne` (
  `studieretning_id` INT NOT NULL,
  `emne_id` INT NOT NULL,
  PRIMARY KEY (`studieretning_id`, `emne_id`),
  INDEX `fk_studieretning_has_emne_emne1_idx` (`emne_id` ASC),
  INDEX `fk_studieretning_has_emne_studieretning1_idx` (`studieretning_id` ASC),
  CONSTRAINT `fk_studieretning_has_emne_studieretning1`
    FOREIGN KEY (`studieretning_id`)
    REFERENCES `datasikkerhet`.`studieretning` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_studieretning_has_emne_emne1`
    FOREIGN KEY (`emne_id`)
    REFERENCES `datasikkerhet`.`emne` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
